# Klasifikasi Prediksi kekambuhan Kanker Tiroid (PRA UAS)

##Data Understading

### Informasi Dataset

Dataset ini berisi 17 fitur klinikopatologis yang bertujuan untuk memprediksi kekambuhan kanker tiroid yang terdefinisi dengan baik. Dataset ini dikumpulkan selama 15 tahun dan setiap pasien diikuti selama setidaknya 10 tahun.

Di dataset ini tidak ada missing value

Sumber : https://archive.ics.uci.edu/dataset/915/differentiated+thyroid+cancer+recurrence



In [2]:
pip install ucimlrepo

In [3]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
differentiated_thyroid_cancer_recurrence = fetch_ucirepo(id=915)

# data (as pandas dataframes)
X = differentiated_thyroid_cancer_recurrence.data.features
y = differentiated_thyroid_cancer_recurrence.data.targets

# metadata
print(differentiated_thyroid_cancer_recurrence.metadata)

# variable information
print(differentiated_thyroid_cancer_recurrence.variables)


{'uci_id': 915, 'name': 'Differentiated Thyroid Cancer Recurrence', 'repository_url': 'https://archive.ics.uci.edu/dataset/915/differentiated+thyroid+cancer+recurrence', 'data_url': 'https://archive.ics.uci.edu/static/public/915/data.csv', 'abstract': 'This data set contains 13 clinicopathologic features aiming to predict recurrence of well differentiated thyroid cancer. The data set was collected in duration of 15 years and each patient was followed for at least 10 years.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 383, 'num_features': 16, 'feature_types': ['Real', 'Categorical', 'Integer'], 'demographics': ['Age', 'Gender'], 'target_col': ['Recurred'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2023, 'last_updated': 'Wed Mar 20 2024', 'dataset_doi': '10.24432/C5632J', 'creators': ['Shiva Borzooei', 'Aidin Tarokhian'], 'intro_paper': {'ID': 333, 'type': 'NA

In [24]:
print(X.head(10))
print(y.head(10).to_string(index=True))
print(X.columns)
print(y.columns)

   Age Gender Smoking Hx Smoking Hx Radiothreapy          Thyroid Function  \
0   27      F      No         No              No                 Euthyroid   
1   34      F      No        Yes              No                 Euthyroid   
2   30      F      No         No              No                 Euthyroid   
3   62      F      No         No              No                 Euthyroid   
4   62      F      No         No              No                 Euthyroid   
5   52      M     Yes         No              No                 Euthyroid   
6   41      F      No        Yes              No  Clinical Hyperthyroidism   
7   46      F      No         No              No                 Euthyroid   
8   51      F      No         No              No                 Euthyroid   
9   40      F      No         No              No                 Euthyroid   

          Physical Examination Adenopathy       Pathology     Focality Risk  \
0   Single nodular goiter-left         No  Micropapillary    U

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# Salin data untuk keamanan
X_encoded = X.copy()

# Encode fitur Boolean dulu (seperti sebelumnya)
from sklearn.preprocessing import LabelEncoder
binary_features = ['Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Adenopathy']
for col in binary_features:
    le = LabelEncoder()
    X_encoded[col] = le.fit_transform(X_encoded[col])

# Encode semua fitur kategorikal menjadi angka dengan OrdinalEncoder
categorical_features = ['Thyroid Function', 'Physical Examination', 'Pathology', 'Focality',
                        'Risk', 'T', 'N', 'M', 'Stage', 'Response']
ordinal_encoder = OrdinalEncoder()
X_encoded[categorical_features] = ordinal_encoder.fit_transform(X_encoded[categorical_features])

# Lihat hasilnya
print(X_encoded.head().to_string(index=False))



 Age  Gender  Smoking  Hx Smoking  Hx Radiothreapy  Thyroid Function  Physical Examination  Adenopathy  Pathology  Focality  Risk   T   N   M  Stage  Response
  27       0        0           0                0               2.0                   3.0           3        2.0       1.0   2.0 0.0 0.0 0.0    0.0       2.0
  34       0        0           1                0               2.0                   1.0           3        2.0       1.0   2.0 0.0 0.0 0.0    0.0       1.0
  30       0        0           0                0               2.0                   4.0           3        2.0       1.0   2.0 0.0 0.0 0.0    0.0       1.0
  62       0        0           0                0               2.0                   4.0           3        2.0       1.0   2.0 0.0 0.0 0.0    0.0       1.0
  62       0        0           0                0               2.0                   1.0           3        2.0       0.0   2.0 0.0 0.0 0.0    0.0       1.0


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Split data
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# 2. Buat model Naive Bayes dan latih
model = GaussianNB()
model.fit(X_train, y_train)

# 3. Prediksi dan evaluasi
y_pred = model.predict(X_test)

# Output evaluasi
print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Akurasi: 0.8831168831168831

Confusion Matrix:
 [[57  1]
 [ 8 11]]

Classification Report:
               precision    recall  f1-score   support

          No       0.88      0.98      0.93        58
         Yes       0.92      0.58      0.71        19

    accuracy                           0.88        77
   macro avg       0.90      0.78      0.82        77
weighted avg       0.89      0.88      0.87        77



/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(X_encoded)

     Age  Gender  Smoking  Hx Smoking  Hx Radiothreapy  Thyroid Function  \
0     27       0        0           0                0               2.0   
1     34       0        0           1                0               2.0   
2     30       0        0           0                0               2.0   
3     62       0        0           0                0               2.0   
4     62       0        0           0                0               2.0   
..   ...     ...      ...         ...              ...               ...   
378   72       1        1           1                1               2.0   
379   81       1        1           0                1               2.0   
380   72       1        1           1                0               2.0   
381   61       1        1           1                1               0.0   
382   67       1        1           0                0               2.0   

     Physical Examination  Adenopathy  Pathology  Focality  Risk    T    N  \
0        

## Modelling

### Naive Bayes Ensemble(gabungan) GaussianNB+CategorikalNB

In [58]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, CategoricalNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, LabelEncoder

# === 1. Pra-pemrosesan Fitur ===

# Fitur numerik dan kategorikal
numerical_features = ['Age']
categorical_features = ['Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function',
                        'Physical Examination', 'Adenopathy', 'Pathology', 'Focality',
                        'Risk', 'T', 'N', 'M', 'Stage', 'Response']

# Salin data
X_num = X[numerical_features].copy()
X_cat = X[categorical_features].copy()

# NORMALISASI fitur numerik
scaler = StandardScaler()
X_num_scaled = scaler.fit_transform(X_num)

# Encoding fitur kategorikal
ordinal_encoder = OrdinalEncoder()
X_cat_encoded = ordinal_encoder.fit_transform(X_cat)

# Gabungkan fitur numerik dan kategorikal
X_combined = np.concatenate([X_num_scaled, X_cat_encoded], axis=1)

# === 2. Encoding Target y ===

le_y = LabelEncoder()
y_encoded = le_y.fit_transform(y)  # "No" -> 0, "Yes" -> 1

# === 3. Split Data ===

X_train, X_test, y_train, y_test = train_test_split(X_combined, y_encoded, test_size=0.2, random_state=42)

# Pisahkan kembali fitur numerik dan kategorikal untuk masing-masing model
X_train_num, X_train_cat = X_train[:, :1], X_train[:, 1:]
X_test_num, X_test_cat = X_test[:, :1], X_test[:, 1:]

# === 4. Modeling ===

# Model Gaussian untuk numerik
gnb = GaussianNB()
gnb.fit(X_train_num, y_train)

# Model Categorical untuk kategorikal
cnb = CategoricalNB()
cnb.fit(X_train_cat, y_train)

# Prediksi probabilitas dari masing-masing model
proba_num = gnb.predict_proba(X_test_num)
proba_cat = cnb.predict_proba(X_test_cat)

# Kombinasi rata-rata probabilitas
combined_proba = (proba_num + proba_cat) / 2
y_pred = np.argmax(combined_proba, axis=1)

# === 5. Evaluasi ===

print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le_y.classes_))


Akurasi: 0.948051948051948

Confusion Matrix:
 [[57  1]
 [ 3 16]]

Classification Report:
               precision    recall  f1-score   support

          No       0.95      0.98      0.97        58
         Yes       0.94      0.84      0.89        19

    accuracy                           0.95        77
   macro avg       0.95      0.91      0.93        77
weighted avg       0.95      0.95      0.95        77



/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Mencari Data Valid untuk data Kategorikal

In [54]:
for i in X[categorical_features].columns:
  print(i)
  print(X[f'{i}'].unique())
  print(" ")
print(X['Physical Examination'].unique())

Gender
['F' 'M']
 
Smoking
['No' 'Yes']
 
Hx Smoking
['No' 'Yes']
 
Hx Radiothreapy
['No' 'Yes']
 
Thyroid Function
['Euthyroid' 'Clinical Hyperthyroidism' 'Clinical Hypothyroidism'
 'Subclinical Hyperthyroidism' 'Subclinical Hypothyroidism']
 
Physical Examination
['Single nodular goiter-left' 'Multinodular goiter'
 'Single nodular goiter-right' 'Normal' 'Diffuse goiter']
 
Adenopathy
['No' 'Right' 'Extensive' 'Left' 'Bilateral' 'Posterior']
 
Pathology
['Micropapillary' 'Papillary' 'Follicular' 'Hurthel cell']
 
Focality
['Uni-Focal' 'Multi-Focal']
 
Risk
['Low' 'Intermediate' 'High']
 
T
['T1a' 'T1b' 'T2' 'T3a' 'T3b' 'T4a' 'T4b']
 
N
['N0' 'N1b' 'N1a']
 
M
['M0' 'M1']
 
Stage
['I' 'II' 'IVB' 'III' 'IVA']
 
Response
['Indeterminate' 'Excellent' 'Structural Incomplete'
 'Biochemical Incomplete']
 
['Single nodular goiter-left' 'Multinodular goiter'
 'Single nodular goiter-right' 'Normal' 'Diffuse goiter']


In [59]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, LabelEncoder
from sklearn.naive_bayes import GaussianNB, CategoricalNB

# PASTIKAN KOLOM DAN TIPE DATANYA SAMA PERSIS DENGAN DATA PELATIHAN ASLI!
# new_data = X.head(3)
new_data = pd.DataFrame({
    'Age': [58, 45, 72],
    'Gender': ['F', 'M', 'F'],
    'Smoking': ['No', 'Yes', 'No'],
    'Hx Smoking': ['No', 'No', 'Yes'],
    'Hx Radiothreapy': ['Yes', 'No', 'No'],
    'Thyroid Function': ['Euthyroid', 'Euthyroid', 'Clinical Hyperthyroidism'],
    'Physical Examination': ['Single nodular goiter-left', 'Single nodular goiter-left', 'Single nodular goiter-left'],
    'Adenopathy': ['No', 'No', 'No'],
    'Pathology': ['Micropapillary', 'Micropapillary', 'Micropapillary'],
    'Focality': ['Uni-Focal', 'Multi-Focal', 'Uni-Focal'],
    'Risk': ['Intermediate', 'High', 'Low'],
    'T': ['T2', 'T4a', 'T1a'],
    'N': ['N0', 'N1b', 'N0'],
    'M': ['M0', 'M1', 'M0'],
    'Stage': ['I', 'IVB', 'I'],
    'Response': ['Excellent', 'Indeterminate', 'Excellent']
})

print("--- Data Baru untuk Prediksi ---")
print(new_data)

# --- 2. Pra-pemrosesan Data Baru ---

# Pisahkan fitur numerik dan kategorikal dari data baru
numerical_features = ['Age'] # Definisikan ulang agar mudah dibaca di sini
categorical_features = ['Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function',
                        'Physical Examination', 'Adenopathy', 'Pathology', 'Focality',
                        'Risk', 'T', 'N', 'M', 'Stage', 'Response'] # Definisikan ulang

new_data_num = new_data[numerical_features].copy()
new_data_cat = new_data[categorical_features].copy()

# Standarisasi fitur numerik menggunakan **scaler yang sudah dilatih**
new_data_num_scaled = scaler.transform(new_data_num)

# Encoding fitur kategorikal menggunakan **ordinal_encoder yang sudah dilatih**
# Jika ada kategori di new_data_cat yang tidak pernah dilihat oleh ordinal_encoder saat fit,
# ini akan menimbulkan ValueError. Pastikan semua kategori di data baru sudah ada di data training.
new_data_cat_encoded = ordinal_encoder.transform(new_data_cat)

# Gabungkan fitur numerik dan kategorikal
new_data_combined = np.concatenate([new_data_num_scaled, new_data_cat_encoded], axis=1)

# Pisahkan kembali untuk prediksi oleh masing-masing model
# Jumlah kolom numerik dan kategorikal harus sama dengan saat pelatihan
num_cols_for_gaussian = len(numerical_features) # Harusnya 1 (untuk 'Age')
num_cols_for_categorical = len(categorical_features) # Harusnya 16

new_data_num_pred = new_data_combined[:, :num_cols_for_gaussian]
new_data_cat_pred = new_data_combined[:, num_cols_for_gaussian : num_cols_for_gaussian + num_cols_for_categorical]

# --- 3. Prediksi dengan Model Ensemble ---

# Prediksi probabilitas dari masing-masing model
new_proba_num = gnb.predict_proba(new_data_num_pred)
new_proba_cat = cnb.predict_proba(new_data_cat_pred)

# Kombinasi rata-rata probabilitas
new_combined_proba = (new_proba_num + new_proba_cat) / 2
new_y_pred_encoded = np.argmax(new_combined_proba, axis=1)

# Mengubah kembali prediksi ke label asli ("No" atau "Yes")
new_y_pred_labels = le_y.inverse_transform(new_y_pred_encoded)

print("\n--- Hasil Prediksi untuk Data Baru ---")
for i, pred_label in enumerate(new_y_pred_labels):
    print(f"Pasien {i+1}: Kekambuhan Kanker Tiroid Diprediksi: {pred_label}")

--- Data Baru untuk Prediksi ---
   Age Gender Smoking Hx Smoking Hx Radiothreapy          Thyroid Function  \
0   58      F      No         No             Yes                 Euthyroid   
1   45      M     Yes         No              No                 Euthyroid   
2   72      F      No        Yes              No  Clinical Hyperthyroidism   

         Physical Examination Adenopathy       Pathology     Focality  \
0  Single nodular goiter-left         No  Micropapillary    Uni-Focal   
1  Single nodular goiter-left         No  Micropapillary  Multi-Focal   
2  Single nodular goiter-left         No  Micropapillary    Uni-Focal   

           Risk    T    N   M Stage       Response  
0  Intermediate   T2   N0  M0     I      Excellent  
1          High  T4a  N1b  M1   IVB  Indeterminate  
2           Low  T1a   N0  M0     I      Excellent  

--- Hasil Prediksi untuk Data Baru ---
Pasien 1: Kekambuhan Kanker Tiroid Diprediksi: No
Pasien 2: Kekambuhan Kanker Tiroid Diprediksi: Yes
Pasien 3

###KNN Classification

In [62]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ASUMSI:
# - Variabel 'X' (fitur dataset asli) dan 'y' (target dataset asli) sudah ada.

# === 1. Pra-pemrosesan Fitur ===

# Definisikan fitur numerik dan kategorikal
numerical_features = ['Age']
categorical_features = ['Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function',
                        'Physical Examination', 'Adenopathy', 'Pathology', 'Focality',
                        'Risk', 'T', 'N', 'M', 'Stage', 'Response']

# Salin data untuk pra-pemrosesan
X_processed = X.copy()

# Standarisasi fitur numerik
scaler = StandardScaler()
X_processed[numerical_features] = scaler.fit_transform(X_processed[numerical_features])

# Encoding fitur kategorikal dengan OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
X_processed[categorical_features] = ordinal_encoder.fit_transform(X_processed[categorical_features])

# Gabungkan semua fitur yang sudah diproses menjadi satu array NumPy
# Pastikan urutan kolom sesuai dengan definisi features Anda
X_combined = X_processed[numerical_features + categorical_features].values


# === 2. Encoding Target y ===
le_y = LabelEncoder()
y_encoded = le_y.fit_transform(y)  # "No" -> 0, "Yes" -> 1

# === 3. Split Data ===
X_train, X_test, y_train, y_test = train_test_split(X_combined, y_encoded, test_size=0.2, random_state=42)

# === 4. Modeling KNN ===

# Inisialisasi model KNN
# n_neighbors=5 adalah nilai K yang umum digunakan, bisa disesuaikan
# metrik 'euclidean' adalah default dan cocok untuk data yang sudah discale
knn = KNeighborsClassifier(n_neighbors=5)

# Latih model KNN
knn.fit(X_train, y_train)

# Prediksi pada data uji
y_pred = knn.predict(X_test)

# === 5. Evaluasi ===

print("--- Hasil Evaluasi Model KNN dengan OrdinalEncoder ---")
print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le_y.classes_))




--- Hasil Evaluasi Model KNN dengan OrdinalEncoder ---
Akurasi: 0.9090909090909091

Confusion Matrix:
 [[57  1]
 [ 6 13]]

Classification Report:
               precision    recall  f1-score   support

          No       0.90      0.98      0.94        58
         Yes       0.93      0.68      0.79        19

    accuracy                           0.91        77
   macro avg       0.92      0.83      0.87        77
weighted avg       0.91      0.91      0.90        77



/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [63]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.compose import ColumnTransformer # Penting untuk menggabungkan pra-pemrosesan

# ASUMSI:
# - Variabel 'X' (fitur dataset asli) dan 'y' (target dataset asli) sudah ada.

# === 1. Pra-pemrosesan Fitur dengan One-Hot Encoding ===

# Definisikan fitur-fitur Anda
numerical_features = ['Age']
# Semua fitur kategorikal akan di-One-Hot Encode
categorical_features = ['Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function',
                        'Physical Examination', 'Adenopathy', 'Pathology', 'Focality',
                        'Risk', 'T', 'N', 'M', 'Stage', 'Response']

# Buat ColumnTransformer untuk menggabungkan pra-pemrosesan
# 'remainder="passthrough"' akan mempertahankan kolom yang tidak disebutkan (misalnya, jika ada kolom lain yang tidak diolah)
# Tetapi di sini kita akan secara eksplisit memilih kolom.
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features) # handle_unknown='ignore' untuk data baru
    ])

# Terapkan pra-pemrosesan pada seluruh dataset X
X_combined = preprocessor.fit_transform(X)

# === 2. Encoding Target y ===
le_y = LabelEncoder()
y_encoded = le_y.fit_transform(y)  # "No" -> 0, "Yes" -> 1

# === 3. Split Data ===
X_train, X_test, y_train, y_test = train_test_split(X_combined, y_encoded, test_size=0.2, random_state=42)

# === 4. Modeling KNN ===

# Inisialisasi model KNN
# n_neighbors=5 adalah nilai K yang umum digunakan, bisa disesuaikan
# metrik 'euclidean' adalah default dan cocok untuk data yang sudah discale dan one-hot encoded
knn = KNeighborsClassifier(n_neighbors=5)

# Latih model KNN
knn.fit(X_train, y_train)

# Prediksi pada data uji
y_pred = knn.predict(X_test)

# === 5. Evaluasi ===

print("--- Hasil Evaluasi Model KNN dengan One-Hot Encoder ---")
print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le_y.classes_))


--- Hasil Evaluasi Model KNN dengan One-Hot Encoder ---
Akurasi: 0.922077922077922

Confusion Matrix:
 [[56  2]
 [ 4 15]]

Classification Report:
               precision    recall  f1-score   support

          No       0.93      0.97      0.95        58
         Yes       0.88      0.79      0.83        19

    accuracy                           0.92        77
   macro avg       0.91      0.88      0.89        77
weighted avg       0.92      0.92      0.92        77



/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [66]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier # Import model KNN
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Asumsi:
# - Variabel 'X' (fitur dataset asli) dan 'y' (target dataset asli) sudah ada.

# --- 1. Pra-pemrosesan Fitur ---

# Definisikan fitur numerik dan kategorikal
numerical_features = ['Age']
categorical_features = ['Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function',
                        'Physical Examination', 'Adenopathy', 'Pathology', 'Focality',
                        'Risk', 'T', 'N', 'M', 'Stage', 'Response']

# Salin data untuk pra-pemrosesan
X_processed = X.copy()

# **Standarisasi fitur numerik**
scaler = StandardScaler()
X_processed[numerical_features] = scaler.fit_transform(X_processed[numerical_features])

# **Encoding fitur kategorikal dengan OrdinalEncoder**
# OrdinalEncoder akan mengubah string menjadi angka integer non-negatif.
# Ini mengasumsikan ada urutan implisit antar kategori, yang mungkin tidak selalu benar.
ordinal_encoder = OrdinalEncoder()
X_processed[categorical_features] = ordinal_encoder.fit_transform(X_processed[categorical_features])

# Gabungkan semua fitur yang sudah diproses menjadi satu array NumPy
# Pastikan urutan kolom sesuai dengan definisi fitur Anda
X_combined = X_processed[numerical_features + categorical_features].values


# --- 2. Encoding Target y ---
# Mengubah target 'Recurred' menjadi angka (0 atau 1)
le_y = LabelEncoder()
y_encoded = le_y.fit_transform(y)  # "No" -> 0, "Yes" -> 1

# --- 3. Split Data ---
# Memisahkan data menjadi set pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X_combined, y_encoded, test_size=0.2, random_state=42)

# --- 4. Modelling KNN ---

# Inisialisasi model KNeighborsClassifier
# n_neighbors: Jumlah tetangga terdekat yang akan dipertimbangkan. Nilai 5 adalah titik awal yang umum.
# metric: Metrik jarak yang digunakan. 'euclidean' adalah default dan cocok untuk data yang sudah discale.
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')

# Latih model KNN pada data pelatihan
knn.fit(X_train, y_train)

# Prediksi pada data uji
y_pred = knn.predict(X_test)

# --- 5. Evaluasi ---

print("--- Hasil Evaluasi Model KNN dengan OrdinalEncoder ---")
print(f"Akurasi: {accuracy_score(y_test, y_pred):.4f}")
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le_y.classes_))

--- Hasil Evaluasi Model KNN dengan OrdinalEncoder ---
Akurasi: 0.9091

Confusion Matrix:
 [[57  1]
 [ 6 13]]

Classification Report:
               precision    recall  f1-score   support

          No       0.90      0.98      0.94        58
         Yes       0.93      0.68      0.79        19

    accuracy                           0.91        77
   macro avg       0.92      0.83      0.87        77
weighted avg       0.91      0.91      0.90        77



/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Klasifikasi dengan metode Decision Tree

In [67]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, LabelEncoder
from sklearn.tree import DecisionTreeClassifier # Import model Decision Tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Asumsi:
# - Variabel 'X' (fitur dataset asli) dan 'y' (target dataset asli) sudah ada.

# === 1. Pra-pemrosesan Fitur ===

# Definisikan fitur numerik dan kategorikal
numerical_features = ['Age']
categorical_features = ['Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function',
                        'Physical Examination', 'Adenopathy', 'Pathology', 'Focality',
                        'Risk', 'T', 'N', 'M', 'Stage', 'Response']

# Salin data untuk pra-pemrosesan agar tidak merusak data asli
X_processed = X.copy()

# **Standardisasi fitur numerik**
# Ini dilakukan untuk konsistensi, meskipun Decision Tree tidak terpengaruh oleh skala.
scaler = StandardScaler()
X_processed[numerical_features] = scaler.fit_transform(X_processed[numerical_features])

# **Encoding fitur kategorikal dengan OrdinalEncoder**
# Mengubah kategori string menjadi representasi numerik (integer non-negatif).
ordinal_encoder = OrdinalEncoder()
X_processed[categorical_features] = ordinal_encoder.fit_transform(X_processed[categorical_features])

# Gabungkan semua fitur yang sudah diproses menjadi satu array NumPy
# Pastikan urutan kolom sesuai dengan definisi fitur Anda
X_combined = X_processed[numerical_features + categorical_features].values


# === 2. Encoding Target y ===
# Mengubah target 'Recurred' menjadi angka (0 atau 1)
le_y = LabelEncoder()
y_encoded = le_y.fit_transform(y)  # "No" -> 0, "Yes" -> 1

# === 3. Split Data ===
# Memisahkan data menjadi set pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X_combined, y_encoded, test_size=0.2, random_state=42)

# === 4. Modelling Decision Tree ===

# Inisialisasi model DecisionTreeClassifier
# random_state=42 untuk memastikan hasil yang sama setiap kali dijalankan.
dt_classifier = DecisionTreeClassifier(random_state=42)

# Latih model Decision Tree pada data pelatihan
dt_classifier.fit(X_train, y_train)

# Prediksi pada data uji
y_pred = dt_classifier.predict(X_test)

# --- 5. Evaluasi ---

print("--- Hasil Evaluasi Model Decision Tree dengan Ordinal Encoding ---")
print(f"Akurasi: {accuracy_score(y_test, y_pred):.4f}")
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le_y.classes_))

--- Hasil Evaluasi Model Decision Tree dengan Ordinal Encoding ---
Akurasi: 0.9221

Confusion Matrix:
 [[54  4]
 [ 2 17]]

Classification Report:
               precision    recall  f1-score   support

          No       0.96      0.93      0.95        58
         Yes       0.81      0.89      0.85        19

    accuracy                           0.92        77
   macro avg       0.89      0.91      0.90        77
weighted avg       0.93      0.92      0.92        77



/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
